spring.application.name=sso_server

auth.server.default.username=admin
auth.server.default.password=admin

# remove later for prod
auth.server.repository.client.name=Test Client
auth.server.repository.client.id=test-client
auth.server.repository.client.secret={noop}test-client
auth.server.repository.redirect.uri=http://localhost:18081/

auth.server.issuer=http://localhost:8843
spring.security.oauth2.authorizationserver.issuer-url=http://localhost:8843

# oauth2 database
spring.datasource.url=jdbc:mysql://localhost:3306/${AUTH_DB_CORE_NAME:auth_server_db}?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&createDatabaseIfNotExist=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.username=${AUTH_DB_USER}
spring.datasource.password=${AUTH_DB_PASS}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.initialization-mode=always

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.jdbc.enable_lazy_load_no_trans=true
spring.jpa.open-in-view=false

server.port=8843

logging.level.root=warn
logging.level.org.springframework.web=debug
logging.level.org.springframework.data.mongodb=debug
logging.level.com.kiraliza.spring=trace
logging.level.org.springframework.data.mongodb.core.MongoTemplate=debug
logging.file.name=./logs/server.log
